Repository AY2324S2-CS2113T-T09-3/tp, pull requests merged in 2024-03, with the labels that each got.

#30 Implemented add product feature
  src/main/java/seedu/stockpal/commands/Command.java
  src/main/java/seedu/stockpal/commands/NewCommand.java
  src/main/java/seedu/stockpal/data/ProductList.java
  src/test/java/seedu/stockpal/commands/NewCommandTest.java
Labels: type.Task

#37 Implement list class
  data/inventory.csv
  src/main/java/seedu/stockpal/StockPal.java
  src/main/java/seedu/stockpal/commands/Command.java
  src/main/java/seedu/stockpal/commands/ListCommand.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/data/ProductList.java
  src/main/java/seedu/stockpal/data/product/Description.java
  src/main/java/seedu/stockpal/data/product/Name.java
  src/main/java/seedu/stockpal/data/product/Pid.java
  src/main/java/seedu/stockpal/data/product/Price.java
  src/main/java/seedu/stockpal/data/product/Product.java
  src/main/java/seedu/stockpal/data/product/Quantity.java
  src/main/java/seedu/stockpal/parser/Parser.java
  src/main/java/seedu/stockpal/storage/Storage.java
  src/main/java/seedu/stockpal/ui/Ui.java
  src/test/java/seedu/stockpal/commands/ListCommandTest.java
Labels: type.Task, priority.High

#39 Fix inflow and outflow product feature
  src/main/java/seedu/stockpal/commands/InflowCommand.java
  src/main/java/seedu/stockpal/data/ProductList.java
  src/main/java/seedu/stockpal/data/product/Product.java
Labels: priority.High

#40 JUnit code + bug fixes
  src/main/java/seedu/stockpal/commands/NewCommand.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/data/ProductList.java
  src/main/java/seedu/stockpal/data/product/Description.java
  src/main/java/seedu/stockpal/data/product/Name.java
  src/main/java/seedu/stockpal/data/product/Price.java
  src/main/java/seedu/stockpal/data/product/Product.java
  src/main/java/seedu/stockpal/data/product/Quantity.java
  src/test/java/seedu/stockpal/commands/NewCommandTest.java
Labels: type.Task, type.Bug, priority.High

#43 Edit inflow outflow error handling
  src/main/java/seedu/stockpal/commands/InflowCommand.java
  src/main/java/seedu/stockpal/commands/OutflowCommand.java
  src/main/java/seedu/stockpal/data/ProductList.java
  src/main/java/seedu/stockpal/data/product/Product.java
  src/main/java/seedu/stockpal/data/product/Quantity.java
  src/main/java/seedu/stockpal/exceptions/InventoryQuantityOverflowException.java
  src/test/java/seedu/stockpal/data/product/QuantityTest.java
Labels: type.Story, priority.High

#45 Created help and exit commands
  data/inventory.csv
  src/main/java/seedu/stockpal/StockPal.java
  src/main/java/seedu/stockpal/commands/DeleteCommand.java
  src/main/java/seedu/stockpal/commands/EditCommand.java
  src/main/java/seedu/stockpal/commands/ExitCommand.java
  src/main/java/seedu/stockpal/commands/HelpCommand.java
  src/main/java/seedu/stockpal/commands/InflowCommand.java
  src/main/java/seedu/stockpal/commands/ListCommand.java
  src/main/java/seedu/stockpal/commands/NewCommand.java
  src/main/java/seedu/stockpal/commands/OutflowCommand.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/parser/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#49 Add assertion and logging
  src/main/java/seedu/stockpal/commands/InflowCommand.java
  src/main/java/seedu/stockpal/commands/OutflowCommand.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/data/product/Quantity.java
Labels: priority.High

#50 Refactor code to reduce coupling between classes.
  .gitignore
  build.gradle
  data/inventory.csv
  src/main/java/seedu/stockpal/StockPal.java
  src/main/java/seedu/stockpal/commands/Command.java
  src/main/java/seedu/stockpal/commands/DeleteCommand.java
  src/main/java/seedu/stockpal/commands/EditCommand.java
  src/main/java/seedu/stockpal/commands/ExitCommand.java
  src/main/java/seedu/stockpal/commands/HelpCommand.java
  src/main/java/seedu/stockpal/commands/InflowCommand.java
  src/main/java/seedu/stockpal/commands/ListActionCommand.java
  src/main/java/seedu/stockpal/commands/ListCommand.java
  src/main/java/seedu/stockpal/commands/NewCommand.java
  src/main/java/seedu/stockpal/commands/OutflowCommand.java
  src/main/java/seedu/stockpal/common/CommandParameter.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/data/ProductList.java
  src/main/java/seedu/stockpal/data/product/Description.java
  src/main/java/seedu/stockpal/data/product/Name.java
  src/main/java/seedu/stockpal/data/product/Pid.java
  src/main/java/seedu/stockpal/data/product/Price.java
  src/main/java/seedu/stockpal/data/product/Product.java
  src/main/java/seedu/stockpal/parser/Parser.java
  src/main/java/seedu/stockpal/storage/Storage.java
  src/main/java/seedu/stockpal/storage/exception/InvalidStorageFilePathException.java
  src/main/java/seedu/stockpal/storage/exception/StorageIOException.java
  src/main/java/seedu/stockpal/ui/Ui.java
  src/test/data/EditCommandTest/Test.csv
  src/test/data/ListCommandTest/ListTest.txt
  src/test/data/NewCommandTest/Test.csv
  src/test/data/StorageTest/AppendedData.csv
  src/test/data/StorageTest/ValidData.csv
  src/test/java/seedu/stockpal/commands/DeleteCommandTest.java
  src/test/java/seedu/stockpal/commands/EditCommandTest.java
  src/test/java/seedu/stockpal/commands/ListCommandTest.java
  src/test/java/seedu/stockpal/commands/NewCommandTest.java
  src/test/java/seedu/stockpal/parser/ParserTest.java
  src/test/java/seedu/stockpal/storage/StorageTest.java
Labels: type.Task, priority.High

#51 Add alerts for outflow
  StorageLogger.log.1
  data/inventory.csv
  src/main/java/seedu/stockpal/StockPal.java
  src/main/java/seedu/stockpal/commands/EditCommand.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/data/ProductList.java
  src/main/java/seedu/stockpal/data/product/Product.java
  src/main/java/seedu/stockpal/data/product/Quantity.java
  src/main/java/seedu/stockpal/ui/Ui.java
  src/test/java/seedu/stockpal/data/product/QuantityTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/data/inventory.csv
Labels: type.Enhancement, priority.Medium

#53 Reformat help page display
  build.gradle
  src/main/java/seedu/stockpal/commands/DeleteCommand.java
  src/main/java/seedu/stockpal/commands/EditCommand.java
  src/main/java/seedu/stockpal/commands/ExitCommand.java
  src/main/java/seedu/stockpal/commands/FindCommand.java
  src/main/java/seedu/stockpal/commands/HelpCommand.java
  src/main/java/seedu/stockpal/commands/InflowCommand.java
  src/main/java/seedu/stockpal/commands/ListCommand.java
  src/main/java/seedu/stockpal/commands/NewCommand.java
  src/main/java/seedu/stockpal/commands/OutflowCommand.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/parser/Parser.java
  src/main/java/seedu/stockpal/ui/Ui.java
  src/test/data/HelpCommandTest/HelpPageTest.txt
  src/test/java/seedu/stockpal/commands/HelpCommandTest.java
Labels: priority.Medium

#60 Add sorting feature to list
  src/main/java/seedu/stockpal/commands/ListCommand.java
  src/main/java/seedu/stockpal/parser/Parser.java
  src/test/java/seedu/stockpal/commands/ListCommandTest.java
Labels: type.Task, priority.Medium

#67 Add skeleton structure, Architecture Diagram and Class Diagram for Storage into Developers Guide.
  .gitignore
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/stockpal/storage/Storage.java
Labels: type.Task, priority.High

#69 Added history command and updated DG
  data/inventory.csv
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandClass.puml
  docs/diagrams/AddCommandSequence.puml
  docs/images/AddCommandClass.png
  docs/images/AddCommandSequence.png
  src/main/java/seedu/stockpal/StockPal.java
  src/main/java/seedu/stockpal/commands/Command.java
  src/main/java/seedu/stockpal/commands/FindCommand.java
  src/main/java/seedu/stockpal/commands/HistoryCommand.java
  src/main/java/seedu/stockpal/commands/InflowCommand.java
  src/main/java/seedu/stockpal/commands/NewCommand.java
  src/main/java/seedu/stockpal/commands/OutflowCommand.java
  src/main/java/seedu/stockpal/commands/TransactionActionCommand.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/data/ProductList.java
  src/main/java/seedu/stockpal/data/Transaction.java
  src/main/java/seedu/stockpal/data/TransactionList.java
  src/main/java/seedu/stockpal/data/product/Product.java
  src/main/java/seedu/stockpal/ui/Ui.java
Labels: type.Task, priority.High

#85 Format User Guide to show segments properly
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#87 Add bug fixes to JSON file loading
  src/main/java/seedu/stockpal/StockPal.java
  src/main/java/seedu/stockpal/storage/Storage.java
  src/main/java/seedu/stockpal/storage/transaction/JsonWriter.java
  src/main/java/seedu/stockpal/storage/transaction/TransactionStorage.java
  src/test/java/seedu/stockpal/storage/transaction/TransactionStorageTest.java
Labels: type.Task, priority.Medium
