Repository AY2324S2-CS2113T-T09-3/tp, pull requests merged in 2024-04, with the labels that each got.

#90 Update help feature user guide
  docs/UserGuide.md
Labels: priority.Medium

#98 Update User Guide
  StorageLogger.log.lck
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/github-icon.png
Labels: type.Task, priority.High

#129 Fix sort feature in list, command usage for UG and class diagram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ListCommandClass.puml
  docs/images/ListCommandClass.png
  src/main/java/seedu/stockpal/commands/ListCommand.java
Labels: type.Bug, priority.Medium

#161 Bug fixes for UG, DG and HelpCommand
  docs/UserGuide.md
  docs/_config.yml
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/images/EditCommandSequenceDiagram.png
  src/main/java/seedu/stockpal/commands/EditCommand.java
  src/test/data/HelpCommandTest/AllCommandsHelpPage.txt
  src/test/data/HelpCommandTest/EditCommandHelpPage.txt
Labels: priority.High

#168 Edit DG, draft PPP, and add fixes to bugs of PED.
  README.md
  StorageLogger.log.lck
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/DataClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/CommandClassDiagram.png
  docs/images/DataClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/ngyaodong.jpg
  docs/team/cheeseong2001.md
  docs/team/edmundtangg.md
  docs/team/kobot7.md
  docs/team/leongxingyu.md
  docs/team/ngyaodong.md
  docs/team/wjunjie01.md
  src/main/java/seedu/stockpal/StockPal.java
  src/main/java/seedu/stockpal/commands/EditCommand.java
  src/main/java/seedu/stockpal/data/CommandParameter.java
  src/main/java/seedu/stockpal/data/product/Description.java
  src/main/java/seedu/stockpal/data/product/Name.java
  src/main/java/seedu/stockpal/data/product/Price.java
  src/main/java/seedu/stockpal/data/product/Quantity.java
  src/main/java/seedu/stockpal/storage/Storage.java
Labels: type.Task, priority.Medium

#174 Add v2.1
  data/inventory.csv
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/InflowCommandSequence.puml
  docs/diagrams/OutflowCommandSequence.puml
  docs/images/InflowCommandSequence.png
  docs/images/OutflowCommandSequence.png
  docs/images/Ui.png
  docs/images/leongxingyu.jpeg
  docs/team/leongxingyu.md
Labels: priority.High

#175 Add fix for bug when deleting product, but transaction still lingering.
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommandClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/CommandClassDiagram.png
  docs/team/ngyaodong.md
  src/main/java/seedu/stockpal/commands/DeleteCommand.java
  src/main/java/seedu/stockpal/data/TransactionList.java
  src/test/java/seedu/stockpal/commands/DeleteCommandTest.java
Labels: type.Task, priority.High

#177 Update DG sequence diagram, PPP and add test coverage
  docs/DeveloperGuide.md
  docs/diagrams/ListCommandSequence.puml
  docs/images/ListCommandExecuteSequenceDiagram.png
  docs/images/wongjunjie.JPG
  docs/team/wjunjie01.md
  src/main/java/seedu/stockpal/commands/ListCommand.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/data/product/Product.java
  src/main/java/seedu/stockpal/parser/Parser.java
  src/main/java/seedu/stockpal/ui/Ui.java
  src/test/data/ListCommandTest/ListSortProductNameTest.txt
  src/test/data/ListCommandTest/ListSortQuantityTest.txt
  src/test/java/seedu/stockpal/commands/ListCommandTest.java
Labels: type.Task, priority.Medium

#178 Update DG, UG and PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditCommandExecuteSequenceDiagram.puml
  docs/images/EditCommandExecuteSequenceDiagram.png
  docs/images/portrait_placeholder.png
  docs/team/kobot7.md
  src/main/java/seedu/stockpal/commands/EditCommand.java
  src/main/java/seedu/stockpal/commands/NewCommand.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/data/ProductList.java
  src/main/java/seedu/stockpal/exceptions/DuplicateProductNameException.java
  src/test/java/seedu/stockpal/commands/EditCommandTest.java
  src/test/java/seedu/stockpal/commands/NewCommandTest.java
Labels: priority.High

#180 Update parser for more specific errors
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/parser/Parser.java
Labels: priority.Medium

#181 Update Help command & DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCommandSequence.puml
  docs/diagrams/EditCommandExecuteSequenceDiagram.puml
  docs/diagrams/InflowCommandSequence.puml
  docs/diagrams/ListCommandSequence.puml
  docs/diagrams/OutflowCommandSequence.puml
  docs/images/DeleteCommandSequence.png
  docs/images/EditCommandExecuteSequenceDiagram.png
  docs/images/InflowCommandSequence.png
  docs/images/ListCommandExecuteSequenceDiagram.png
  docs/images/OutflowCommandSequence.png
  src/main/java/seedu/stockpal/commands/DeleteCommand.java
  src/main/java/seedu/stockpal/commands/EditCommand.java
  src/main/java/seedu/stockpal/commands/ExitCommand.java
  src/main/java/seedu/stockpal/commands/FindCommand.java
  src/main/java/seedu/stockpal/commands/HelpCommand.java
  src/main/java/seedu/stockpal/commands/HistoryCommand.java
  src/main/java/seedu/stockpal/commands/InflowCommand.java
  src/main/java/seedu/stockpal/commands/ListCommand.java
  src/main/java/seedu/stockpal/commands/NewCommand.java
  src/main/java/seedu/stockpal/commands/OutflowCommand.java
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/ui/Ui.java
  src/test/data/HelpCommandTest/AllCommandsHelpPage.txt
  src/test/data/HelpCommandTest/DeleteCommandHelpPage.txt
  src/test/data/HelpCommandTest/EditCommandHelpPage.txt
  src/test/data/HelpCommandTest/HelpPageTest.txt
  src/test/data/HelpCommandTest/HistoryCommandHelpPage.txt
  src/test/data/HelpCommandTest/ListCommandHelpPage.txt
  src/test/data/HelpCommandTest/NewCommandHelpPage.txt
Labels: priority.High

#183 Update Parser to be case insensitive
  docs/UserGuide.md
  src/main/java/seedu/stockpal/parser/Parser.java
Labels: priority.Medium

#184 Fix detection of duplicate PID, names bug in storage file
  StorageLogger.log.lck
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/diagrams/AddCommandExecuteSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommandSequenceDiagram.puml
  docs/diagrams/DeleteCommandSequence.puml
  docs/diagrams/HistoryCommandExecuteSequenceDiagram.puml
  docs/diagrams/InflowCommandSequence.puml
  docs/diagrams/ListCommandSequence.puml
  docs/diagrams/OutflowCommandSequence.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddCommandExecuteSequenceDiagram.png
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/CommandSequenceDiagram.png
  docs/images/DeleteCommandSequence.png
  docs/images/HistoryCommandExecuteSequenceDiagram.png
  docs/images/InflowCommandSequence.png
  docs/images/ListCommandExecuteSequenceDiagram.png
  docs/images/OutflowCommandSequence.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/Windows-home-folder.png
  docs/team/ngyaodong.md
  src/main/java/seedu/stockpal/common/Messages.java
  src/main/java/seedu/stockpal/data/ProductList.java
  src/main/java/seedu/stockpal/exceptions/PidDuplicateException.java
  src/main/java/seedu/stockpal/parser/Parser.java
  src/main/java/seedu/stockpal/storage/Storage.java
  src/main/java/seedu/stockpal/storage/transaction/TransactionStorage.java
  src/main/java/seedu/stockpal/ui/Ui.java
Labels: type.Task, priority.High

#194 Update help page for edit and find command
  src/main/java/seedu/stockpal/commands/EditCommand.java
  src/main/java/seedu/stockpal/commands/FindCommand.java
  src/test/data/HelpCommandTest/AllCommandsHelpPage.txt
  src/test/data/HelpCommandTest/EditCommandHelpPage.txt
  src/test/data/HelpCommandTest/FindCommandHelpPage.txt
Labels: priority.High
